before_install:
  - sudo apt-get install -y libasound2-dev libmpg123-dev libatlas-base-dev cuda-cudart-10-0
  - sudo sh install_kaldi.sh
  - pip install cython
language: python
python:
  - 3.5
  - 3.7
dist: xenial
sudo: true
script: pytest
services:
  - postgresql
before_script:
  - psql -U postgres -d postgres -c "CREATE USER pynab; ALTER ROLE pynab CREATEDB;"
