before_install:
  - sudo apt-get install -y libasound2-dev libmpg123-dev libatlas-base-dev
  - sudo sh install_kaldi.sh
  - pip install cython
language: python
python:
  - 3.5
  - 3.7
dist: xenial
sudo: true
script:
  - python -m snips_nlu download fr
  - python -m snips_nlu download en
  - python -m snips_nlu generate-dataset en pynab/*/nlu/intent_en.yaml > pynab/nabd/nlu/nlu_dataset_en.json
  - python -m snips_nlu generate-dataset fr pynab/*/nlu/intent_fr.yaml > pynab/nabd/nlu/nlu_dataset_fr.json
  - snips-nlu train pynab/nabd/nlu/nlu_dataset_en.json pynab/nabd/nlu/engine_en
  - snips-nlu train pynab/nabd/nlu/nlu_dataset_fr.json pynab/nabd/nlu/engine_fr
  - pytest
services:
  - postgresql
before_script:
  - psql -U postgres -d postgres -c "CREATE USER pynab; ALTER ROLE pynab CREATEDB;"
