name: Release image

on:
  push:
    branches:
      [ releng ]
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the branch
      id: get_branch
      run: |
        if [ ${GITHUB_REF/refs\/tags\//} != ${GITHUB_REF} ]; then
          echo ::set-output name=BRANCH::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=IMAGE_NAME_SUFFIX::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=IMAGE_PATH::"pynab.img.xz"
        elif [ ${GITHUB_REF/refs\/heads\//} = "releng" ]; then
          echo ::set-output name=BRANCH::releng
          echo ::set-output name=IMAGE_NAME_SUFFIX::releng
          echo ::set-output name=IMAGE_PATH::"pynab-prerelease.img.xz"
        else
          echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}
          echo ::set-output name=IMAGE_NAME_SUFFIX::${GITHUB_REF/refs\/heads\//}
          echo ::set-output name=IMAGE_PATH::"pynab.img.xz"
        fi
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y qemu qemu-user-static binfmt-support parted wget dosfstools zip
    - name: Create image
      run: sudo TRAVIS_BRANCH=${{ steps.get_branch.outputs.BRANCH }} bash ./create-image
    - uses: actions/upload-artifact@v2
      with:
        name: Pynab image (${{ steps.get_branch.outputs.IMAGE_NAME_SUFFIX }})
        path: ${{ steps.get_branch.outputs.IMAGE_PATH }}
